config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'blocks#index'
  post '/search' => 'header#search'
  get '/api' => 'application#api'

  resources :blocks, only: [:index, :show] do
    collection do
      get 'block', action: :show
    end
  end

  resources :transactions, only: [:index, :show] do
    collection do
      get 'transaction', action: :show
    end
  end

  resources :addresses, only: [:index, :show] do
    collection do
      get 'address', action: :show
    end
  end

  resources :peers, only: [:index]
  resources :stats, only: [:index]

  # Custom routes
  get '/info' => 'application#api'
  get '/tx/:tx_hash' => 'transactions#show'
  get '/richlist' => 'addresses#index'
  get '/network' => 'peers#index'
  get '/movement' => 'blocks#index'
  get '/ext/getmoneysupply' => 'stats#getmoneysupply'
end

app/models/block.rb
class Block < ActiveRecord::Base

  # Associations
  has_many :transactions

  # Calculates value out for each block by adding up total value out of each transaction
  #
  # Author:: Sambhav Sharma
  # Date:: 04/12/2017
  # Reviewed By::
  #
  def value_out
    stake_value > 0 ? stake_value : transactions.collect(&:value_out).inject(&:+)
  end

  # Calculates total coins created as stake
  #
  # Author:: Sambhav Sharma
  # Date:: 04/12/2017
  # Reviewed By::
  #
  def stake_value
    transactions.collect(&:stake_value).inject(&:+)
  end
end

app/controllers/blocks_controller.rb
# First point of contact for all block requests to the application
# Author:: Sambhav Sharma
class BlocksController < ApplicationController

  # Actions
  before_action :set_stats, only: [:index, :show]

  # Renders the index page for Blocks
  #
  # Author:: Sambhav Sharma
  # Date:: 04/12/2017
  # Reviewed By::
  #
  def index
    @blocks = Block.includes(transactions: :outputs).all.order(block_index: :desc)
                  .paginate(page: params[:page], per_page: params[:per_page] || GlobalConstant::DEFAULT_PER_PAGE)

    respond_to do |format|
      format.json do
        render json: @blocks, status: 200
      end

      format.html
    end
  end

  # Renders the show page for a block
  #
  # Author:: Sambhav Sharma
  # Date:: 04/12/2017
  # Reviewed By::
  #
  def show
    if params[:block_hash].present?
      block_query = { block_hash: params[:block_hash]}
    elsif params[:block_index].present?
      block_query = {block_index: params[:block_index]}
    elsif params[:id].present?
      block_query = {id: params[:id]}
    else
      block_query = {}
    end

    @block = Block.includes(transactions: :outputs).find_by(block_query)

    respond_to do |format|
      format.json do
        render json: @block, status: 200
      end

      format.html
    end
  end
end

app/views/blocks/index.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#blocks" data-toggle="tab">Blocks</a></li>
</ul>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Index</th>
      <th>Block Hash</th>
      <th>Age</th>
      <th>Transactions</th>
      <th>Total Output</th>
      <th>Difficulty</th>
    </tr>
  </thead>
  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td> <%= link_to block.block_index, block_path(block) %> </td>
        <td> <%= link_to block.block_hash, block_path(block) %> </td>
        <td> <%= time_ago_in_words(block.time) %> </td>
        <td class="center"> <%= block.transactions.length %> </td>
        <td> <%= number_to_human(block.value_out) %> </td>
        <td> <%= block.difficulty %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row center">
  <%= will_paginate @blocks, previous_label: '<', next_label: '>', inner_window: 1, outer_window: 3 %>
</div>

app/views/blocks/show.html.erb
<div class="row">
  <h2>
    <span class="hidden-xs">Details for </span>Block #<%= @block.block_index %>
  </h2>
  <table class="table" id="details">
    <tbody>
      <tr>
        <td>Hash</td>
        <td>
          <% if @block.block_index > 0 %>
            <%= link_to block_blocks_path({block_index: @block.block_index - 1}) do %>
              <span class="glyphicon glyphicon-chevron-left"></span>
            <% end %>
          <% end %>

          <code class="hash">
            <%= @block.block_hash %>
          </code>

          <% if Block.where(block_index: @block.block_index + 1).count > 0  %>
            <%= link_to block_blocks_path({block_index: @block.block_index + 1}) do %>
                <span class="glyphicon glyphicon-chevron-right"></span>
            <% end %>
          <% end %>
        </td>
      </tr>

      <tr>
        <td>Date/Time</td>
        <td>
          <%= @block.time %>
        </td>
      </tr>

      <tr>
        <td>Transactions</td>
        <td>
          <%= @block.transactions.length %>
        </td>
      </tr>

      <tr>
        <td>Value Out</td>
        <td class="amount">
          <%= number_to_human(@block.value_out) %> <%= GlobalConstant::COIN_SYMBOL %>
        </td>
      </tr>

      <tr>
        <td>Difficulty</td>
        <td><%= @block.difficulty %></td>
      </tr>

      <tr>
        <td>Confirmations</td>
        <td> <%= CachedData::total_blocks - @block.block_index %> </td>
      </tr>
      <tr>
        <td>
          <b>Created</b>
        </td>
        <td class="amount">
          <%= @block.stake_value %> <%= GlobalConstant::COIN_SYMBOL %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<ul class="nav nav-tabs">
  <li class="active"><a href="#blocks" data-toggle="tab">Transactions</a></li>
</ul>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Transaction Hash</th>
    <th>Transaction Type</th>
    <th>Confirmations</th>
    <th>Value Out</th>
  </tr>
  </thead>
  <tbody>
  <% @block.transactions.each do |tx| %>
      <tr>
        <td> <%= link_to tx.tx_hash, transaction_path(tx) %> </td>
        <td> <%= tx.tx_type.titleize %> </td>
        <td class="center"> <%= CachedData::total_blocks - @block.block_index %> </td>
        <td> <%= tx.value_out %> </td>
      </tr>
  <% end %>
  </tbody>
</table>