config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'blocks#index'
  post '/search' => 'header#search'
  get '/api' => 'application#api'

  resources :blocks, only: [:index, :show] do
    collection do
      get 'block', action: :show
    end
  end

  resources :transactions, only: [:index, :show] do
    collection do
      get 'transaction', action: :show
    end
  end

  resources :addresses, only: [:index, :show] do
    collection do
      get 'address', action: :show
    end
  end

  resources :peers, only: [:index]
  resources :stats, only: [:index]

  # Custom routes
  get '/info' => 'application#api'
  get '/tx/:tx_hash' => 'transactions#show'
  get '/richlist' => 'addresses#index'
  get '/network' => 'peers#index'
  get '/movement' => 'blocks#index'
  get '/ext/getmoneysupply' => 'stats#getmoneysupply'
end

app/controllers/addresses_controller.rb
# First point of contact for all address requests to the application
# Author:: Sambhav Sharma
class AddressesController < ApplicationController

  # Actions
  before_action :set_stats, only: [:index, :show]

  # Renders the index page for Addresses
  #
  # Author:: Sambhav Sharma
  # Date:: 09/12/2017
  # Reviewed By::
  #
  def index
    @addresses = Address.where("balance > ?", 0).order(balance: :desc)
                  .paginate(page: params[:page], per_page: params[:per_page] || GlobalConstant::DEFAULT_PER_PAGE,
                            total_entries: 500)

    respond_to do |format|
      format.json do
        render json: @addresses, status: 200
      end

      format.html
    end
  end

  # Renders the show page for a address
  #
  # Author:: Sambhav Sharma
  # Date:: 04/12/2017
  # Reviewed By::
  #
  def show
    if params[:address].present?
      ad_query = { address: params[:address]}
    elsif params[:id].present?
      ad_query = {id: params[:id]}
    else
      ad_query = {}
    end

    @address = Address.includes(:input_transactions, :output_transactions).find_by(ad_query)
    @input_transactions = @address.input_transactions
                              .paginate(page: params[:it_page], per_page: params[:it_per_page] || GlobalConstant::DEFAULT_PER_PAGE)
    @output_transactions = @address.output_transactions
                              .paginate(page: params[:ot_page], per_page: params[:ot_per_page] || GlobalConstant::DEFAULT_PER_PAGE)

    respond_to do |format|
      format.json do
        render json: @address, status: 200
      end

      format.html
    end
  end
end

app/views/addresses/_addresses_table.html.erb
<table class="table table-striped table-condensed">
  <thead>
  <tr>
    <th>Rank</th>
    <th>Address</th>
    <th>Balance (NLC2)</th>
    <th>%</th>
  </tr>
  </thead>
  <tbody>
  <% addresses.each_with_index do |addr, index| %>
      <tr>
        <td><%= offset + index %></td>
        <td align="left">
          <%= link_to addr.address, address_path(addr) %>
        </td>
        <td align="left">
          <%= "%.8f" %addr.balance %> NLC2
        </td>
        <td >
          <%= number_to_human(addr.coin_percentage) %>%
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<% if paginate %>
  <div class="row center">
    <%= will_paginate addresses, previous_label: '<', next_label: '>', inner_window: 1, outer_window: 3 %>
  </div>
<% end %>

app/views/addresses/_wealth_chart.html.erb
<script type="text/javascript">

  // Load the Visualization API and the corechart package.
  google.charts.load('current', {'packages':['corechart']});

  // Set a callback to run when the Google Visualization API is loaded.
  google.charts.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Wallets');
    data.addColumn('number', 'Coins');

    <%
     rows = []
     CachedData.wealth_distribution_graph.each do |key, value|
      rows.push([key.to_s.titleize, value])
     end
    %>

    data.addRows(<%= rows.to_json.html_safe %>);

    // Set chart options
    var options = {
      height: 250,
      legend: {
        position: 'none'
      },
      chartArea:{width:'100%',height:'90%', top: 10}
    };

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>

app/views/addresses/index.html.erb
<div class="row center">
  <div class="col-md-8 mbm">
  <h4 class="left">Addresses</h4>
  <%= render 'addresses/addresses_table', addresses: @addresses, offset: @addresses.offset + 1, paginate: true %>
  </div>
  <div class="col-md-4">
    <h4 class="left">Wealth Distribution</h4>
    <table class="table table-striped table-condensed" id="wealth-distribution">
      <thead>
      <tr>
        <th>Top addresses</th>
        <th>Amount (NLC2)</th>
        <th>Percentage</th>
      </tr>
      </thead>
      <tbody>
      <% CachedData.wealth_distribution.each do |key, data| %>
          <tr>
            <td>
              <%= key.to_s.titleize %>
            </td>
            <td><%= number_to_human(data[:holdings])%> NLC2</td>
            <td><%= number_to_human(data[:percentage])%> %</td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>
  </div>
</div>



<%= render 'wealth_chart' %>

app/views/addresses/show.html.erb
<% @tx = Transaction.last %>
<div class="row">
  <h2>
    <span class="hidden-xs">Details for Address </span>
  </h2>
  <table class="table" id="details">
    <tbody>
    <tr>
      <td>Address</td>
      <td> <%= @address.address %> </td>
    </tr>

    <tr>
      <td>Balance</td>
      <td> <%= @address.balance %> NLC2 </td>
    </tr>

    <tr>
      <td>Received</td>
      <td> <%= @address.total_received %> NLC2 </td>
    </tr>

    <tr>
      <td>Staked</td>
      <td> <%= @address.total_staked %> NLC2 </td>
    </tr>

    <tr>
      <td>Sent</td>
      <td> <%= @address.total_spent %> NLC2 </td>
    </tr>
    </tbody>
  </table>
</div>

<table class="table table-hover">
  <thead>
  <tr class="table-section"><td colspan="4"><h3>Received</h3></td></tr>
  <tr>
    <th>Transaction Hash</th>
    <th>Date/Time</th>
    <th>Transaction Type</th>
    <th>Confirmations</th>
    <th>Value Out</th>
  </tr>
  </thead>
  <tbody>
  <% @output_transactions.each do |tx| %>
      <tr>
        <td> <%= link_to tx.tx_hash, transaction_path(tx) %> </td>
        <td> <%= tx.block.time %> </td>
        <td> <%= tx.tx_type.titleize %> </td>
        <td class="center"> <%= tx.confirmations %> </td>
        <td> <%= tx.stake_value || tx.value_out %> </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="row center">
  <%= will_paginate @output_transactions, previous_label: '<', next_label: '>', inner_window: 1, outer_window: 3,
                    :param_name => 'ot_page' %>
</div>

<table class="table table-hover">
  <thead>
  <tr class="table-section"><td colspan="4"><h3>Spent</h3></td></tr>
  <tr>
    <th>Transaction Hash</th>
    <th>Date/Time</th>
    <th>Transaction Type</th>
    <th>Confirmations</th>
    <th>Value Out</th>
  </tr>
  </thead>
  <tbody>
  <% @input_transactions.each do |tx| %>
      <tr>
        <td> <%= link_to tx.tx_hash, transaction_path(tx) %> </td>
        <td> <%= tx.block.time %> </td>
        <td> <%= tx.tx_type.titleize %> </td>
        <td class="center"> <%= tx.confirmations %> </td>
        <td> <%= tx.stake_value || tx.value_out %> </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="row center">
  <%= will_paginate @input_transactions, previous_label: '<', next_label: '>', inner_window: 1, outer_window: 3,
                    :param_name => 'it_page' %>
</div>